### ISSUE TITLE
Workflow and Readme Implementation

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/Colourblind8#21]
Starting from this milestone, you must follow the GitHub Flow workflow. Each team member must do at least one review and each member must have some part of their code reviewed by other team members.

* [x]  Hayley
* [x]  Sabrina
* [x]  Ian

Python Readme Update

- [x] Installation
- [x] Usage

**Comment by sabrinatkk** [comment]
Readme fully updated.

**Comment by sabrinatkk** [comment]
@ian-flores @hfboyce Great job team. I think we can close this now.
